name: secret_code
description: "A new Flutter project."
publish_to: 'none'
version: 3.0.1+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Per le chiamate API
  http: ^1.2.0
  # Per la versione app
  package_info_plus: ^5.0.1
  # Per generare ID univoci (Utente Ospite)
  uuid: ^4.3.3
  # Per salvare dati locali (ID ospite)
  shared_preferences: ^2.2.2
  # Per aprire link
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true